### ISSUE TITLE
Efficiency for Information Retrieval

### ISSUE THREAD

**Issue by poke19962008** [Sandeeprds95/zoho_marks#1]
It is taking O(731) at worst case. If you store all the information in a database with proper keys it would become O(1)
Check Out this:
https://github.com/poke19962008/Zoho-SmartAnswer/blob/master/scrapper/main.py

**Comment by Sandeeprds95** [comment]
Yeah. Actually I just did that in about an hour for timepass. Will make it efficient. Before I look at your code, what exactly have you done? Just created your own DB and stored all the values and then accessing it in O(1)?

**Comment by poke19962008** [comment]
Yup, created a proper schema(present in README.md file) of the collection and stored it in Mongo.  Took 25min to scrap the entire 2nd Yr. CSE record(731 students).

Have used mongo so that I can efficiently get answers for complex queries i.e "students passed in maths"

**Comment by Sandeeprds95** [comment]
Okay cool. I'll perhaps just get it done using hashing of the registration numbers, with the direct URLs of that student's ZOHO web page. For accessing by names, maybe chain hashing or something. I'll have to look it up.
